apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.general.app}}"
  name: "{{ .Values.general.name}}"
  namespace: "{{ .Values.general.namespace}}"
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: "{{ .Values.general.app}}"
  
