apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: "{{ .Values.general.namespace}}"
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: "{{ .Values.postgresql.port}}"
    targetPort: "{{ .Values.postgresql.port}}"
  selector:
    app: db
  
