apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: "{{ .Values.general.name}}"
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: "{{ .Values.redis.port}}"
  selector:
    app: redis
  
