apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: "{{ .Values.general.namespace}}"
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: {{ .Values.result_vote.port }}
    targetPort: {{ .Values.result_vote.targetPort }}
    nodePort: {{ .Values.result_vote.nodePort }}
  selector:
    app: result
