apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: "{{ .Values.general.namespace}}"
spec:
  replicas: {{ .Values.image_vote.replicas }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
#      - image: dockersamples/examplevotingapp_vote:before
      - image: "{{ .Values.image_vote.repository }}:{{ .Values.image_vote.tag}}"
        imagePullPolicy: {{ .Values.image_vote.pullPolicy }}
        name: vote
        ports:
        - containerPort: {{ .Values.image_vote.containerPort }}
          name: vote
