apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: "{{ .Values.general.namespace}}"
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: {{ .Values.vote_service.port}}
    targetPort: {{ .Values.vote_service.targetPort}}
    nodePort: {{ .Values.vote_service.nodePort}}
  selector:
    app: vote
  
